# Add 'dns-opts": [ "ndots:15" ]' to daemon.json to allow usage of other than FQDN
# when using alpine-images


version: '3'

services:
  api:
    build: ./api
    volumes:
      - ./api/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    depends_on:
      - fan-service
      - temperature-service
  
  fan-service:
    build: ./fan-service
    volumes:
      - ./fan-service:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 5000

  temperature-service:
    build: ./temperature-service
    volumes:
      - ./temperature-service:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 5000